#!/usr/bin/env node
/**
 * Copy the committed sample bundle into public/data.
 *
 * public/data is a build output and is gitignored, so a fresh clone has no
 * bundle at all: the dev server, the unit suite and the production build would
 * all read a directory that is not there. fixtures/synthetic is the committed
 * source of truth, and this is the one step that turns it into a servable
 * bundle. Run it after a clone, and again whenever the fixtures change.
 *
 * The destination is emptied first. Leaving stale files behind is how a bundle
 * that no longer contains a site keeps serving the old one, which is exactly
 * the class of failure the sample data exists to avoid.
 *
 *   node scripts/seed-data.mjs
 */
import { cpSync, existsSync, mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const repo = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const source = join(repo, 'fixtures', 'synthetic')
const destination = join(repo, 'public', 'data')

if (!existsSync(source)) {
  console.error(
    `No sample bundle at ${source}. It is generated by ` +
      `ingest/src/atlas_ingest/synthetic.py and committed; regenerate it with ` +
      `PYTHONPATH=ingest/src python3 -m atlas_ingest.synthetic`,
  )
  process.exit(1)
}

if (existsSync(destination)) {
  for (const entry of readdirSync(destination)) {
    // .gitkeep is what keeps public/data present in a fresh clone.
    if (entry === '.gitkeep') continue
    rmSync(join(destination, entry), { recursive: true, force: true })
  }
}

mkdirSync(destination, { recursive: true })
cpSync(source, destination, { recursive: true })
writeFileSync(join(destination, '.gitkeep'), '')

const files = []
const walk = (dir, prefix = '') => {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) walk(join(dir, entry.name), `${prefix}${entry.name}/`)
    else if (entry.name.endsWith('.json')) files.push(`${prefix}${entry.name}`)
  }
}
walk(destination)

console.log(`Seeded public/data with ${files.length} file(s) from fixtures/synthetic.`)
